remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Optional settings
title: "TeleSparse"
description: "Practical Privacy-Preserving Verification of Deep Neural Networks"
baseurl: "/TeleSparse"

